# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer
import random
import math

class Ui_MainWindow(object):

    timeout = QtCore.pyqtSignal
    def __init__(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(100, 100, 500, 500))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsScene = QtWidgets.QGraphicsScene()
        self.graphicsScene.sceneRect()
        self.graphicsView.setSceneRect(QtCore.QRectF(100,100,300,300))
        self.graphicsView.setScene(self.graphicsScene)
        self.pixitem = QtWidgets.QGraphicsPixmapItem(QtGui.QPixmap("C:/Users/89332/Desktop/but3.jpg"))
        self.graphicsScene.addItem(self.pixitem)
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.ope)
        self.timer.start(200)
        self.x = 260
        self.y = 260
        self.up = True

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

    def ope(self):
        a = random.randint(0,2)
        angle = random.randint(0,360)
        lon = random.randint(0,20)
        if self.up == True:
            pi = QtGui.QPixmap("C:/Users/89332/Desktop/but5.jpg")
            self.pixitem.setPixmap(pi)
            self.up = False;
        else:
            self.up = True;
            pi = QtGui.QPixmap("C:/Users/89332/Desktop/but6.jpg")
            self.pixitem.setPixmap(pi)

        if self.x >= 500 - pi.width() / 2:
            self.x = 0
        elif self.y >= 500 - pi.height() / 2:
            self.y = 0
        if a == 0:
            self.x += 20
        elif a == 1:
            self.y += 20
        elif a == 2:
            self.x += math.sin(angle)*lon
            self.y += math.cos(angle)*5
        self.pixitem.setPos(self.x, self.y)